### ISSUE TITLE
Scenarios

### ISSUE THREAD

**Issue by LillyPHIL** [domokane/DicePy#1]
Hey domokane, 

I'm currently working on a project using the model but unfortunately, the "scenarios" script says it has not enough "arguments" for the output function; is it my mistake? or does it in general not work ? 

All the best and thx

--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/Downloads/DicePy-master/dicepy/run_scenarios.py in <module>
     57     x_start = np.concatenate([MIU_start, S_start])
     58 
---> 59     output = simulateDynamics(x_start, *args)
     60 
     61     dumpState(years, output, "./results/scenarioOutput.csv")

TypeError: not enough arguments: expected 46, got 43

**Comment by domokane** [comment]
Don't use that - use run_optimizer.

**Comment by LillyPHIL** [comment]
Thanks a lot, I did and it worked out well but I'd need to simulate different scenarios of climate change mitigation policy as well?
